// Mocks generated by Mockito 5.4.5 from annotations
// in nookly/test/presentation/bloc/conversation/disappearing_image_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nookly/core/network/socket_service.dart' as _i6;
import 'package:nookly/domain/entities/conversation.dart' as _i2;
import 'package:nookly/domain/entities/message.dart' as _i5;
import 'package:nookly/domain/repositories/conversation_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConversation_0 extends _i1.SmartFake implements _i2.Conversation {
  _FakeConversation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i3.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Conversation>> getConversations() => (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.Conversation>>.value(<_i2.Conversation>[]),
      ) as _i4.Future<List<_i2.Conversation>>);

  @override
  _i4.Future<Map<String, dynamic>> getMessages({
    required String? participantId,
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [],
          {
            #participantId: participantId,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.Conversation> getConversation(
    String? participantId,
    String? participantName,
    String? participantAvatar,
    bool? isOnline,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversation,
          [
            participantId,
            participantName,
            participantAvatar,
            isOnline,
          ],
        ),
        returnValue: _i4.Future<_i2.Conversation>.value(_FakeConversation_0(
          this,
          Invocation.method(
            #getConversation,
            [
              participantId,
              participantName,
              participantAvatar,
              isOnline,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Conversation>);

  @override
  _i4.Future<void> sendTextMessage(
    String? conversationId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTextMessage,
          [
            conversationId,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendVoiceMessage(
    String? conversationId,
    String? audioPath,
    Duration? duration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVoiceMessage,
          [
            conversationId,
            audioPath,
            duration,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendFileMessage(
    String? conversationId,
    String? filePath,
    String? fileName,
    int? fileSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFileMessage,
          [
            conversationId,
            filePath,
            fileName,
            fileSize,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendImageMessage(
    String? conversationId,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendImageMessage,
          [
            conversationId,
            imagePath,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markMessageAsRead(String? messageId) => (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [messageId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> blockUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unblockUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> muteConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteConversation,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unmuteConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteConversation,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> leaveConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveConversation,
          [conversationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Message>> listenToMessages(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenToMessages,
          [conversationId],
        ),
        returnValue: _i4.Stream<List<_i5.Message>>.empty(),
      ) as _i4.Stream<List<_i5.Message>>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i6.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isSocketConnected => (super.noSuchMethod(
        Invocation.getter(#isSocketConnected),
        returnValue: false,
      ) as bool);

  @override
  void connect({
    required String? serverUrl,
    required String? token,
    required String? userId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #serverUrl: serverUrl,
            #token: token,
            #userId: userId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendMessage(Map<String, dynamic>? message) => super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendEncryptedMessage(
    String? receiverId,
    String? messageContent,
    String? messageType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEncryptedMessage,
          [
            receiverId,
            messageContent,
            messageType,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> decryptMessage(
    Map<String, dynamic>? message,
    String? senderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptMessage,
          [
            message,
            senderId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  void sendImageViewed(
    String? messageId,
    String? conversationId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendImageViewed,
          [
            messageId,
            conversationId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendImageExpired(
    String? messageId,
    String? conversationId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendImageExpired,
          [
            messageId,
            conversationId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnect() => super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(
    String? event,
    dynamic data,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #emit,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on(
    String? event,
    dynamic Function(dynamic)? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void off(String? event) => super.noSuchMethod(
        Invocation.method(
          #off,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void offSpecific(
    String? event,
    dynamic Function(dynamic)? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #offSpecific,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendGameInvite({
    required String? gameType,
    required String? otherUserId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendGameInvite,
          [],
          {
            #gameType: gameType,
            #otherUserId: otherUserId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void acceptGameInvite({
    required String? gameType,
    required String? otherUserId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #acceptGameInvite,
          [],
          {
            #gameType: gameType,
            #otherUserId: otherUserId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void rejectGameInvite({
    required String? gameType,
    required String? fromUserId,
    String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #rejectGameInvite,
          [],
          {
            #gameType: gameType,
            #fromUserId: fromUserId,
            #reason: reason,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void completeGameTurn({
    required String? sessionId,
    String? selectedChoice,
    required Map<String, dynamic>? selectedPrompt,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #completeGameTurn,
          [],
          {
            #sessionId: sessionId,
            #selectedChoice: selectedChoice,
            #selectedPrompt: selectedPrompt,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void endGame({
    required String? sessionId,
    required String? reason,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #endGame,
          [],
          {
            #sessionId: sessionId,
            #reason: reason,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendHeartbeat() => super.noSuchMethod(
        Invocation.method(
          #sendHeartbeat,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startHeartbeat({Duration? interval = const Duration(seconds: 30)}) =>
      super.noSuchMethod(
        Invocation.method(
          #startHeartbeat,
          [],
          {#interval: interval},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopHeartbeat() => super.noSuchMethod(
        Invocation.method(
          #stopHeartbeat,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logRegisteredListeners() => super.noSuchMethod(
        Invocation.method(
          #logRegisteredListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
