// Mocks generated by Mockito 5.4.5 from annotations
// in nookly/test/presentation/bloc/received_likes/received_likes_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nookly/domain/entities/recommended_profile.dart' as _i4;
import 'package:nookly/domain/entities/recommended_profiles_page.dart' as _i5;
import 'package:nookly/domain/repositories/recommended_profiles_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RecommendedProfilesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendedProfilesRepository extends _i1.Mock
    implements _i2.RecommendedProfilesRepository {
  MockRecommendedProfilesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.RecommendedProfilesPage> getRecommendedProfiles({
    double? radius,
    int? limit,
    String? cursor,
    List<String>? physicalActiveness,
    List<String>? availability,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedProfiles,
          [],
          {
            #radius: radius,
            #limit: limit,
            #cursor: cursor,
            #physicalActiveness: physicalActiveness,
            #availability: availability,
          },
        ),
        returnValue: _i3.Future<_i5.RecommendedProfilesPage>.value(
            _i5.RecommendedProfilesPage(
          profiles: const <_i4.RecommendedProfile>[],
          hasMore: false,
        )),
      ) as _i3.Future<_i5.RecommendedProfilesPage>);

  @override
  _i3.Future<void> likeProfile(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #likeProfile,
          [profileId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dislikeProfile(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #dislikeProfile,
          [profileId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.RecommendedProfile>> getLikedProfiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedProfiles,
          [],
        ),
        returnValue: _i3.Future<List<_i4.RecommendedProfile>>.value(
            <_i4.RecommendedProfile>[]),
      ) as _i3.Future<List<_i4.RecommendedProfile>>);

  @override
  _i3.Future<List<_i4.RecommendedProfile>> getProfilesThatLikedMe() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfilesThatLikedMe,
          [],
        ),
        returnValue: _i3.Future<List<_i4.RecommendedProfile>>.value(
            <_i4.RecommendedProfile>[]),
      ) as _i3.Future<List<_i4.RecommendedProfile>>);
}
