// Mocks generated by Mockito 5.4.5 from annotations
// in nookly/test/presentation/pages/profile/edit_profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nookly/data/models/auth/auth_response_model.dart' as _i2;
import 'package:nookly/data/models/auth/forgot_password_response_model.dart'
    as _i4;
import 'package:nookly/data/models/auth/login_request_model.dart' as _i10;
import 'package:nookly/data/models/auth/otp_response_model.dart' as _i6;
import 'package:nookly/data/models/auth/register_request_model.dart' as _i11;
import 'package:nookly/data/models/auth/reset_password_response_model.dart'
    as _i5;
import 'package:nookly/data/models/auth/verify_otp_response_model.dart' as _i7;
import 'package:nookly/domain/entities/user.dart' as _i3;
import 'package:nookly/domain/repositories/auth_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseModel_0 extends _i1.SmartFake
    implements _i2.AuthResponseModel {
  _FakeAuthResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgotPasswordResponseModel_2 extends _i1.SmartFake
    implements _i4.ForgotPasswordResponseModel {
  _FakeForgotPasswordResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseModel_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseModel {
  _FakeResetPasswordResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOtpResponseModel_4 extends _i1.SmartFake
    implements _i6.OtpResponseModel {
  _FakeOtpResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyOtpResponseModel_5 extends _i1.SmartFake
    implements _i7.VerifyOtpResponseModel {
  _FakeVerifyOtpResponseModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i8.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.AuthResponseModel> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i9.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.AuthResponseModel>);

  @override
  _i9.Future<_i2.AuthResponseModel> signUpWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i9.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #signUpWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i2.AuthResponseModel>);

  @override
  _i9.Future<_i3.User> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i9.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i9.Future<_i3.User>);

  @override
  _i9.Future<_i4.ForgotPasswordResponseModel> forgotPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i9.Future<_i4.ForgotPasswordResponseModel>.value(
            _FakeForgotPasswordResponseModel_2(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i9.Future<_i4.ForgotPasswordResponseModel>);

  @override
  _i9.Future<_i5.ResetPasswordResponseModel> resetPassword(
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            token,
            newPassword,
          ],
        ),
        returnValue: _i9.Future<_i5.ResetPasswordResponseModel>.value(
            _FakeResetPasswordResponseModel_3(
          this,
          Invocation.method(
            #resetPassword,
            [
              token,
              newPassword,
            ],
          ),
        )),
      ) as _i9.Future<_i5.ResetPasswordResponseModel>);

  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i9.Future<_i3.User?>.value(),
      ) as _i9.Future<_i3.User?>);

  @override
  _i9.Future<void> updateUserProfile(_i3.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [user],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.AuthResponseModel> login(_i10.LoginRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.AuthResponseModel>);

  @override
  _i9.Future<_i2.AuthResponseModel> register(
          _i11.RegisterRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #register,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.AuthResponseModel>);

  @override
  _i9.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<List<String>> getPredefinedInterests() => (super.noSuchMethod(
        Invocation.method(
          #getPredefinedInterests,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> getPredefinedObjectives() => (super.noSuchMethod(
        Invocation.method(
          #getPredefinedObjectives,
          [],
        ),
        returnValue: _i9.Future<List<String>>.value(<String>[]),
      ) as _i9.Future<List<String>>);

  @override
  _i9.Future<_i6.OtpResponseModel> sendOtp(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [email],
        ),
        returnValue:
            _i9.Future<_i6.OtpResponseModel>.value(_FakeOtpResponseModel_4(
          this,
          Invocation.method(
            #sendOtp,
            [email],
          ),
        )),
      ) as _i9.Future<_i6.OtpResponseModel>);

  @override
  _i9.Future<_i7.VerifyOtpResponseModel> verifyOtp(
    String? email,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            email,
            otp,
          ],
        ),
        returnValue: _i9.Future<_i7.VerifyOtpResponseModel>.value(
            _FakeVerifyOtpResponseModel_5(
          this,
          Invocation.method(
            #verifyOtp,
            [
              email,
              otp,
            ],
          ),
        )),
      ) as _i9.Future<_i7.VerifyOtpResponseModel>);

  @override
  _i9.Future<_i6.OtpResponseModel> resendOtp(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOtp,
          [email],
        ),
        returnValue:
            _i9.Future<_i6.OtpResponseModel>.value(_FakeOtpResponseModel_4(
          this,
          Invocation.method(
            #resendOtp,
            [email],
          ),
        )),
      ) as _i9.Future<_i6.OtpResponseModel>);
}
